import {Router} from "express";
import { CreateTagController } from "./controllers/CreateTagController";
import { ensureAdmin } from "./middlewares/EnsureAdmin";
import { AuthenticateUserController } from "./controllers/AuthenticateUserController";
import { CreateComplimentController } from "./controllers/CreateComplimentController";
import { ensureAuthenticated } from "./middlewares/ensureAuthenticated";
import { ListUserSendComplimentsController } from "./controllers/ListUserSendComplimentController";
import { ListUserReceiveComplimentsController } from "./controllers/ListUserReceiveComplimentController";
import { ListTagsController } from "./controllers/ListTagsController";
import { UserController } from "./controllers/UserController";
const router = Router();
const createTagController=new CreateTagController();
const authenticateUserController=new AuthenticateUserController();
const complimentController=new CreateComplimentController();
const listUserSendComplimentsController=new ListUserSendComplimentsController();
const listUserReceiveComplimentController=new ListUserReceiveComplimentsController();
const listTagsController=new ListTagsController();
const userController = new UserController();
router.post("/users", userController.create);
router.delete("/users", userController.delete);
router.get("/users", userController.read);
router.put("/users", userController.update);
router.post("/tags",ensureAuthenticated,ensureAdmin,createTagController.handle);
router.post("/login",authenticateUserController.handle);
router.post("/compliments",ensureAuthenticated,complimentController.handle);
router.get("/users/compliments/send",ensureAuthenticated,listUserSendComplimentsController.handle);
router.get("/users/compliments/receive",ensureAuthenticated,listUserReceiveComplimentController.handle);
router.get("/tags",listTagsController.handle);
export {router};